---
- name: Create or modify AWS Secrets Manager secrets
  community.aws.secretsmanager_secret:
    access_key: "{{ lookup('ansible.builtin.env', 'AWS_ACCESS_KEY_ID') }}"
    secret_key: "{{ lookup('ansible.builtin.env', 'AWS_SECRET_ACCESS_KEY') }}"
    state: "{{ secrets_aws_secret_state }}"
    name: "{{ secrets_aws_secret_name }}"
    secret: "{{ secrets_aws_secret_value }}"
    secret_type: "{{ secrets_aws_secret_type | default(omit, true) }}"
    json_secret: "{{ secrets_aws_json_secret_value }}"
    description: "{{ item.description | default(omit) }}"
    kms_key_id: "{{ secrets_aws_kms_key_id | default(omit, true) }}"
    overwrite: "{{ secrets_aws_overwrite }}"
    recovery_window: "{{ secrets_aws_recovery_window }}"
    region: "{{ secrets_aws_region }}"
    resource_policy: "{{ secrets_aws_resource_policy if secrets_aws_resource_policy is not none else omit }}"
    replica: "{{ secrets_aws_replica if secrets_aws_replica is not none else omit }}"
    rotation_lambda: "{{ secrets_aws_rotation_lambda | default(omit, true) }}"
    rotation_interval: "{{ secrets_aws_rotation_interval if secrets_aws_rotation_interval is not none else omit }}"
    endpoint_url: "{{ secrets_aws_endpoint_url | default(omit, true) }}"
    aws_ca_bundle: "{{ secrets_aws_ca_bundle | default(omit, true) }}"
    aws_config: "{{ secrets_aws_config if secrets_aws_config is not none else omit }}"
    validate_certs: "{{ secrets_aws_validate_certs }}"
    debug_botocore_endpoint_logs: "{{ secrets_aws_debug_botocore_endpoint_logs if secrets_aws_debug_botocore_endpoint_logs is not none else omit }}"
    tags: "{{ secrets_aws_tags | combine({'Cluster': patroni_cluster_name}) }}"
    purge_tags: false
  vars:
    secrets_aws_secret_name: >-
      {{
        ((secrets_prefix | regex_replace('/+$', '')) ~ '/' if secrets_prefix | length > 0 else '')
        ~ (item.name | regex_replace('^/+', ''))
      }}
    secrets_aws_secret_state: "{{ item.state | default('present') }}"
    secrets_aws_secret_is_json: >-
      {{ item.value is mapping or (item.value is sequence and item.value is not string) }}
    secrets_aws_secret_value: >-
      {{
        (item.value | string)
        if secrets_aws_secret_state == 'present' and not secrets_aws_secret_is_json
        else omit
      }}
    secrets_aws_json_secret_value: >-
      {{
        item.value
        if secrets_aws_secret_state == 'present' and secrets_aws_secret_is_json
        else omit
      }}
  loop: "{{ secrets_items }}"
  loop_control:
    label: "{{ item.name }}"
  delegate_to: localhost
  become: false
  run_once: true
  no_log: true
  diff: false
