---
- name: Manage secrets with AWS Secrets Manager
  ansible.builtin.include_tasks: aws.yml
  vars:
    postgresql_user_secret_items: >-
      {{
        hostvars['localhost']['postgresql_users_for_secrets'] | default([])
        if secrets_export_postgresql_users | bool
        else []
      }}
    connection_info_secret_items: >-
      {{
        [{'name': secrets_connection_info_path, 'value': hostvars['localhost']['connection_info_for_secrets']}]
        if secrets_export_connection_info | bool
        and hostvars['localhost']['connection_info_for_secrets'] is defined
        else []
      }}
    secrets_items: "{{ secrets_values + postgresql_user_secret_items + connection_info_secret_items }}"
  when:
    - secrets_provider | lower == 'aws'
    - secrets_items | length > 0
